services:
  # Backend API
  - type: web
    name: spendsmart-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: spendsmart-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  # Frontend
  - type: web
    name: spendsmart-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://spendsmart-api.onrender.com/api

databases:
  - name: spendsmart-db
    databaseName: spendsmart
    user: admin 